prod:
  image: vizzuality/widget-adapter:1.0.0${STAGING}
  ports:
    - "3050"
  env_file:
    - prod.env
  command: start
  dns: ${DNS_SERVER}
  restart: always
  log_driver: "syslog"
  log_opt:
      syslog-address: ${SYSLOG_ADDRESS}
      tag: widget-adapter${STAGING}
