version: "2"
services:
  develop:
    extends:
      file: base.yml
      service: base
    ports:
      - "35749:35749"
    environment:
      CT_URL: http://mymachine:9000
      LOCAL_URL: http://mymachine:3050
      CT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      API_VERSION: v1
      CT_REGISTER_MODE: auto
      REDIS_URL: redis://redis:6379
    command: develop
    depends_on:
      - mongo
    volumes:
      - ./app:/opt/widget/app

  mongo:
    image: mongo:3.4
    container_name: widget-mongo-develop
    command: --smallfiles
    ports:
      - "27017"
    volumes:
      - /tmp/docker/data/widget/mongo:/data/db
    restart: always
