version: "2"
services:
  develop:
    extends:
      file: base.yml
      service: base
    ports:
      - "35749:35749"
    environment:
      CT_URL: http://mymachine:9000
      LOCAL_URL: http://mymachine:3050
      CT_TOKEN: null
      API_VERSION: v1
      CT_REGISTER_MODE: auto
    command: develop
    volumes:
      - ./app:/opt/widget/app

  mongo:
    image: mongo:3.4
    container_name: widget-mongo-develop
    command: --smallfiles
    ports:
      - "27017"
    volumes:
      - /tmp/docker/data/widget/mongo:/data/db
    restart: always
