version: "2"
services:
  test:
    extends:
      file: base.yml
      service: base
    ports:
      - "3050"
    container_name: widget-adapter-test
    environment:
      NODE_ENV: test
      CT_URL: http://mymachine:9000
      command: test
