version: "2"
services:
  test:
    extends:
      file: base.yml
      service: base
    ports:
      - "3050"
    container_name: widget-adapter-test
    environment:
      NODE_ENV: test
      CT_URL: http://mymachine:9000
      CT_REGISTER_MODE: auto
      API_VERSION: v1
    command: test
    links:
    - mongo

  mongo:
    image: mongo:3.4
    command: --smallfiles
    ports:
    - "27017"
    restart: always

